name: clinical_intelligence_platform

description: Clinical Intelligence Platform

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.2.1

  provider: ^6.1.2

  shared_preferences: ^2.2.3

  speech_to_text: ^7.0.0

  flutter_tts: ^4.0.2

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  jwt_decoder: ^2.0.1

  dio: ^5.4.3+1

  connectivity_plus: ^6.0.3

  permission_handler: ^11.3.1

  flutter_secure_storage: ^9.2.2

  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - lib/localization/en.json
    - lib/localization/ur.json
